// Package launcher generates and installs the Zen Sync.app bundle, a
// minimal .app whose only job is to exec `zen-sync open` so the user can
// put it in the Dock.
package launcher

import (
	"fmt"
	"os"
	"path/filepath"
)

// Install creates a minimal .app bundle at appPath. The bundle's executable
// is a short bash stub that exec's `<binaryPath> open` (forwarding any
// args the .app receives, like a URL).
func Install(appPath, binaryPath, bundleID, displayName string) error {
	macOSDir := filepath.Join(appPath, "Contents", "MacOS")
	if err := os.MkdirAll(macOSDir, 0o755); err != nil {
		return err
	}

	// Info.plist
	info := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>launcher</string>
    <key>CFBundleIdentifier</key><string>%s</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>%s</string>
    <key>CFBundleDisplayName</key><string>%s</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>11.0</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
`, bundleID, displayName, displayName)

	if err := os.WriteFile(filepath.Join(appPath, "Contents", "Info.plist"), []byte(info), 0o644); err != nil {
		return err
	}

	// Launcher shell stub. Forwards extra args (Zen treats them as URLs/files).
	stub := fmt.Sprintf(`#!/bin/bash
# Auto-generated by zen-sync. Edit only if you know what you are doing.
exec %q open "$@"
`, binaryPath)
	stubPath := filepath.Join(macOSDir, "launcher")
	if err := os.WriteFile(stubPath, []byte(stub), 0o755); err != nil {
		return err
	}
	return nil
}

// Uninstall removes the .app bundle. Missing is treated as success.
func Uninstall(appPath string) error {
	if err := os.RemoveAll(appPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
