// Package launcher generates and installs the Zen Sync.app bundle, a
// minimal .app whose only job is to exec `zen-sync open` so the user can
// put it in the Dock.
//
// Install always rewrites; Ensure compares the embedded commit hash with
// the running binary's and only regenerates when they differ — this is how
// `brew upgrade zen-sync` automatically picks up new icons, plist tweaks,
// or any other bundle change without the user re-running `init`.
package launcher

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
)

//go:embed icon.icns
var iconICNS []byte

// commitRe extracts the build-time commit hash from the marker comment we
// embed at the top of generated plists. Same pattern works for the launcher
// .app's Info.plist and the LaunchAgent plist.
var commitRe = regexp.MustCompile(`IOZenSyncCommit:(\S+)`)

// Install creates a minimal .app bundle at appPath, overwriting any existing
// contents. version + commit are recorded in the Info.plist so Ensure can
// detect a stale bundle after a binary upgrade.
func Install(appPath, binaryPath, bundleID, displayName, version, commit string) error {
	macOSDir := filepath.Join(appPath, "Contents", "MacOS")
	if err := os.MkdirAll(macOSDir, 0o755); err != nil {
		return err
	}
	resDir := filepath.Join(appPath, "Contents", "Resources")
	if err := os.MkdirAll(resDir, 0o755); err != nil {
		return err
	}

	info := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!-- IOZenSyncCommit:%s IOZenSyncVersion:%s -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>launcher</string>
    <key>CFBundleIconFile</key><string>icon</string>
    <key>CFBundleIdentifier</key><string>%s</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleName</key><string>%s</string>
    <key>CFBundleDisplayName</key><string>%s</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>%s</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>11.0</string>
    <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
`, commit, version, bundleID, displayName, displayName, version)

	if err := os.WriteFile(filepath.Join(appPath, "Contents", "Info.plist"), []byte(info), 0o644); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(resDir, "icon.icns"), iconICNS, 0o644); err != nil {
		return err
	}

	stub := fmt.Sprintf(`#!/bin/bash
# Auto-generated by zen-sync. Edit only if you know what you are doing.
exec %q open "$@"
`, binaryPath)
	stubPath := filepath.Join(macOSDir, "launcher")
	return os.WriteFile(stubPath, []byte(stub), 0o755)
}

// Ensure regenerates the bundle iff the embedded commit differs from the
// supplied one — or the bundle doesn't exist yet. Returns whether anything
// changed.
//
// Reading a missing or marker-less Info.plist counts as "needs regenerate",
// which also handles users upgrading from a pre-Ensure release that had no
// commit marker.
func Ensure(appPath, binaryPath, bundleID, displayName, version, commit string) (bool, error) {
	info, err := os.ReadFile(filepath.Join(appPath, "Contents", "Info.plist"))
	if err == nil {
		if m := commitRe.FindStringSubmatch(string(info)); len(m) == 2 && m[1] == commit {
			return false, nil
		}
	}
	if err := Install(appPath, binaryPath, bundleID, displayName, version, commit); err != nil {
		return false, err
	}
	return true, nil
}

// Uninstall removes the .app bundle. Missing is treated as success.
func Uninstall(appPath string) error {
	if err := os.RemoveAll(appPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
